version: '3'
services:

  sonarqube:
    container_name: sonarqube
    image: sonarqube:latest
    ports:
      - "12345:9000"
      - "50001:50000"
    networks:
      integracao:
         ipv4_address: 172.20.0.3

networks:
 integracao:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/16
